import Image from "next/image";
import Link from "next/link";

const Acessibilidade = () => (
    <article>
<div >
   <p>Normalmente, o início da puberdade traz consigo um enorme conjunto de mudanças físicas e psicológicas por conta da ação dos hormônios sexuais – especialmente a testosterona e o estrogênio. Algumas das alterações causadas são irreversíveis, como o padrão de crescimento ósseo ou o engrossamento das cordas vocais. Outras características só são reversíveis com procedimentos especializados: isso inclui pelos faciais ou crescimento mamário.&nbsp;&nbsp;</p>
   <p>Pessoas trans costumam sentir grande desconforto com essas mudanças, e podem buscar métodos para modificá-las. Há uma série de profissionais que podem ser consultados a fim de se ter acesso a tratamentos que ajudam a aliviar a disforia. Neste artigo, vamos falar brevemente de alguns dos principais profissionais especializados nestes tratamentos e sobre como funciona o acesso a eles no Brasil.</p>
   <h3 >Tratamentos e transição de gênero</h3>
   <p>Psicólogos e psiquiatras podem tanto ajudar uma pessoa a se perceber trans como também fornecer um suporte muito importante para a <strong>saúde psicológica</strong> de pessoas trans, auxiliando-as no enfrentamento à transfobia, na construção de uma rede de apoio, no processo de “sair do armário", com questões com transfobia internalizada e outros <Link href="https://biapagliarinibagagli.medium.com/3-verdades-mais-importantes-sobre-a-sa%C3%BAde-da-popula%C3%A7%C3%A3o-trans-2ba50dc0bd23">sentimentos negativos comumente vivenciados por minorias</Link> e em lidar com a disforia em geral.</p>
   <p>Endocrinologistas são os médicos responsáveis pela<strong> terapia hormonal</strong>, que consiste na administração de hormônios do gênero com a qual a pessoa se identifica a fim de que ela desenvolva características sexuais secundárias desse gênero. Além de mudanças físicas, a terapia hormonal promove também mudanças a nível neurológico que trazem bem-estar psicológico. Esse profissional também faz acompanhamento dos níveis hormonais e de outros exames a fim de proteger a saúde da pessoa trans ao longo do tratamento. No Brasil, apenas maiores de 16 anos e com autorização dos pais podem realizar terapia hormonal.</p>
   <p>Fonoaudiólogos fazem treinos com o intuito de feminizar ou masculinizar <strong>a voz</strong>. Esse tratamento é bastante importante principalmente para pessoas trans femininas, pois a hormonização feminizante não altera a voz, para elas o treino de voz é ferramenta fundamental na modificação vocal. A hormonização masculinizante, por outro lado, engrossa as cordas vocais permanentemente, o que diminui a necessidade pessoas trans masculinas buscarem esse tratamento, embora possa ainda assim trazer benefícios. Via de regra, tal tratamento está disponível apenas no sistema particular.</p>
   <p>Existe também uma vasta gama de <strong>cirurgias </strong>que podem trazer benefícios para pessoas trans (cirurgias afirmativas de gênero), como cirurgias genitais, faciais, mastectomia ou implantes mamários. No Brasil é exigido de 1 a 2 anos de acompanhamento psicológico antes da pessoa poder realizar cirurgias transgenitalizadoras</p>
   <p>Por fim, embora não seja considerada um procedimento médico, a <strong>depilação permanente </strong>também é bastante importante no tratamento da disforia, principalmente de pessoas trans femininas, pois os pelos de algumas áreas do corpo não sofrem alteração com a terapia hormonal. Infelizmente, a remoção de pelos não é fornecida nem pelo SUS e nem coberta por planos de saúde, sendo considerada com frequência mero “tratamento estético". No Brasil, este tipo de serviço costuma ser oferecido por clínicas especializadas em depilação com luz pulsada, depilação a laser ou eletrólise.</p>
   <h3 >Serviços públicos de saúde trans no Brasil</h3>
   <p>A criação de protocolos para tratamentos voltados a pessoas trans no Sistema Único de Saúde (SUS) no Brasil é bastante recente. Ainda que hoje esses serviços sejam muito mais acessíveis que no passado, ainda há muita desinformação e irregularidades na prestação de serviços médicos a pessoas trans. Isso leva a um senso geral de que é necessário uma mistura de sorte e de alguns privilégios para se ter acesso efetivo a esses tratamentos no Brasil, pois a acessibilidade varia muito de acordo com as regiões. São Paulo, por exemplo, concentra muito mais ambulatórios da rede pública que atendem demandas de pessoas trans do que o resto do país.&nbsp;</p>
   <p>Além disso, a complexidade do funcionamento do sistema de saúde frequentemente é um obstáculo para pessoas trans, que podem acabar encaminhadas em ‘ping-pong’, indo de clínicos-gerais para endocrinologistas e destes para médicos psiquiatras e psicólogos até conseguirem finalmente encontrar quem possa ajudá-la a conseguir o tratamento que procura. Por conta disso, algumas pessoas acabam tendo um acesso rápido e eficiente no tratamento do SUS e outras acabam tendo uma espera que pode parecer infinita. Para pessoas que já fazem psicoterapia há algum tempo, levar um laudo psicológico apontando o quadro da disforia de gênero, embora não seja necessário, é algo que pode agilizar o atendimento.</p>
   <p>Uma vez admitida para tratamento no SUS e com o pedido médico em mãos, a pessoa trans pode requisitar os medicamentos para iniciar sua transição hormonal nas farmácias do SUS. Também é possível ir diretamente às farmácias do SUS caso a pessoa já tenha a receita médica exigida. Contudo, não é incomum que, devido a atraso nas consultas ou falta de medicamentos, pessoas trans dependentes desta via acabem perdendo acesso aos medicamentos que necessitam e interrompendo sua hormonização, o que pode levar a sérios problemas. Além disso, conforme comentamos no artigo ‘<Link href="https://disforiadegenero.com.br/alivio-disforia/">Como aliviar a disforia?</Link>‘, alguns dos medicamentos disponibilizados pelo SUS para a TH feminizante não são ideais e <Link data-type="URL" data-id="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6628137/" href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6628137/" target="_blank" rel="noreferrer noopener">estão associados a um alto risco de trombose</Link>.</p>
   <p>Quando uma pessoa inicia tratamentos relacionados à transição no SUS, ela também pode entrar na lista de espera para cirurgias afirmativas de gênero, o que pode levar bastante tempo. Embora o número de cirurgias afirmativas realizadas viesse aumentando até 2019, o número de procedimentos caiu drasticamente com a pandemia, agravando a situação de quem busca esses tratamentos pela rede pública. Hoje em dia, <Link href="https://www1.folha.uol.com.br/cotidiano/2021/01/cirurgias-de-readequacao-sexual-desabam-na-pandemia-e-espera-da-populacao-trans-se-agrava.shtml" target="_blank" rel="noreferrer noopener">a fila pode levar até 18 anos</Link>. A <Link href="https://antrabrasil.org/" target="_blank" rel="noreferrer noopener">ANTRA</Link> possui <Link href="https://antrabrasil.org/2020/07/27/como-acessar-o-sus-para-questoes-de-transicao/" target="_blank" rel="noreferrer noopener">um guia detalhando esses e outros aspectos do acesso a procedimentos cirúrgicos no SUS</Link>.</p>
   <p>A seguir temos uma lista dos de serviços públicos que atendem a população trans:</p>
   <figure ><Image decoding="async" src="" alt="" /></figure>
   <h3 >Sistema particular</h3>
   <p>No sistema particular, o cenário também varia: muitos endocrinologistas, seja por preconceito ou despreparo, não estão aptos ou não se sentem confortáveis tratando pessoas trans, muito embora o tratamento hormonal com pessoas trans não exige conhecimentos muito diferentes da formação geral em endocrinologia.&nbsp;</p>
   <p>Além disso, muitos dos que aceitam atender pessoas trans ainda seguem modelos de tratamento antiquados e questionáveis. Por exemplo, é comum que seja receitado a mulheres trans um regime hormonal com doses desnecessariamente altas de bloqueadores de testosterona junto a doses baixas de estrogênio, uma combinação que muitas vezes causa efeitos colaterais perigosos. Hoje em dia <Link href="https://transfemscience.org/articles/cpa-dosage/">sabe-se que doses baixas de bloqueador são suficientes</Link>, e que para boa parte das pessoas o uso de estradiol por si só (monoterapia) já é capaz de suprimir a produção de testosterona.</p>
   <p>É comum também que endocrinologistas exijam um laudo de avaliação de saúde mental antes de iniciar a hormonização. Em teoria, isso poderia cumprir uma função de cuidado com a saúde mental da paciente, inclusive, essa é a lógica que fundamenta a diretriz atual de tratamento do <Link href="https://www.in.gov.br/en/web/dou/-/resolucao-n-2.265-de-20-de-setembro-de-2019-237203294">Conselho Federal de Medicina (CFM)</Link>. Porém, na prática isso significa a aplicação de uma série de regras que acabam restringindo o acesso da população trans aos tratamentos que precisam.</p>
   <p>Um argumento típico para a exigência desse laudo é de que uma pessoa, por conta de algum transtorno psicológico e estando fora de seu próprio discernimento, poderia se confundir sobre ser transgênero e vir a se arrepender da transição no futuro. Por mais “bem intencionado" que tal tipo de argumento pretenda ser, é uma justificativa bastante rasa e que acaba por criar obstáculos que prejudicam pessoas trans e reforçam a patologização desse grupo (mais sobre isso em breve no artigo “Diagnósticos e disforia de gênero").&nbsp;</p>
   <p>Alguns médicos psiquiatras (seguindo uma interpretação incorreta do <Link href="https://pt.wikipedia.org/wiki/Diagnostic_and_Statistical_Manual_of_Mental_Disorders">DSM-V</Link>) obrigam pacientes trans a passarem por longas avaliações (que podem durar mais de 6 meses) antes de conceder o laudo de avaliação de saúde mental comumente exigido por endocrinologistas. Outros ainda defendem que, antes de um paciente transicionar, é sempre necessário tratar quaisquer outros transtornos psicológicos que possam afetar seu julgamento. Esse tipo de raciocínio, refletido em recomendações do CFM e outros órgãos, é fatalmente equivocado, pois ignora que o desconforto derivado da disforia de gênero muito frequentemente é responsável pela manifestação de sintomas similares aos de distúrbios comuns como ansiedade ou depressão. Em outras palavras, pode ser impossível se livrar de transtornos do tipo antes uma transição se eles derivam do quadro de disforia de gênero.&nbsp;</p>
   <p>Inclusive, <Link href="https://biapagliarinibagagli.medium.com/o-que-a-pesquisa-acad%C3%AAmica-diz-sobre-o-efeito-da-transi%C3%A7%C3%A3o-de-g%C3%AAnero-sobre-o-bem-estar-transg%C3%AAnero-9770a6d50e21">vários estudos</Link> apontam os benefícios imediatos da transição para a saúde mental de pessoas trans. Se há alguma razão verdadeiramente válida para que pessoas trans sejam incentivadas (e não obrigadas) a procurar psicoterapia, ela parte do fato de que o Brasil é um país bastante violento e com várias dificuldades para pessoas trans. Por conta disso é importante que a pessoa tenha algumas reflexões sobre como ela lidará com a reação social à sua transição, a que redes de apoio ela poderá recorrer e quais serviços ou instituições podem ajudá-la neste processo.</p>
   <p>Por mais que o cenário acima pareça desanimador para quem busca iniciar sua transição médica, existem profissionais conscientes dos benefícios que tais procedimentos podem trazer à saúde de pessoas trans, e que buscam descomplicar burocracias em seus atendimentos, por exemplo, abrindo mão da exigência de um laudo psicológico e adotando o modelo de consentimento informado, em que a própria pessoa se declara responsável pela decisão de iniciar o tratamento. Em geral, esses profissionais mais receptivos costumam ser indicados em fóruns online de pessoas trans.</p>
   <p>Para o caso de cirurgias, é possível que haja cobertura de planos de saúde para cirurgias que visam tratar a disforia de gênero, sendo que algumas delas já estão mais integradas nos pacotes dos planos (em geral cirurgia genital, mastectomia e implante mamário) e outras ainda requerem processo judicial para serem aprovadas. Em todo caso, é exigida uma comprovação médica do quadro de disforia de gênero para os planos de saúde.&nbsp;</p>
</div>
    </article>
  )

export default Acessibilidade;
