import Link from "next/link";

const Expressao = () => (
    <article>
<div >
   <p>Roupas, cabelo, maquiagem, jóias, óculos, piercings e outras modificações corporais. Até a higiene pessoal pode ser um fator de apresentação, como a depilação dos pelos do corpo ou a maneira como você cuida da pele. Todas essas expressões são associadas a gênero na nossa sociedade, especialmente roupas e cabelos.</p>
   <p>Embora a revolução sexual da década de 1960 e a mania da moda empresarial dos anos 80 tenham feito maravilhas para estreitar a linha entre a apresentação masculina e feminina (em grande parte normalizando a moda masculina como andrógina), ainda existem enormes pressões para se conformar às normas de gênero tradicionais. Formas de se vestir que não conformam às normas de gênero são reconhecidas como dissonantes tão rápido que basta um homem usar um vestido ou mesmo uma camiseta com cores mais vivas para ser rotulado de homossexual.</p>
   <p>Cabelo comprido em homens tem sido visto como um ato de rebeldia de roqueiros por décadas, e homens com cabelo comprido dificilmente são vistos como “profissionais" ou “competentes". Cabelo curto em mulheres é frequentemente lido como queer ou butch (a menos que sejam mais velhas, então é esperado), e mulheres muitas vezes são pressionadas a manter o cabelo comprido. Homens com orelhas furadas tornaram-se um pouco mais normalizados nos anos 90, mas ainda são mal vistos em vários meios, especialmente em profissões mais conservadoras. A maquiagem nos homens é tão estigmatizada pela masculinidade tóxica que mesmo os homens que gostam de maquiagem se sentem pressionados a não usá-la.</p>
   <p>Goste ou não, a apresentação é baseada no gênero, e é extremamente comum para as pessoas trans desejarem ter uma apresentação mais alinhada com seu verdadeiro gênero, e o desejo de se livrar dos grilhões da apresentação baseada no gênero é comum entre todas as pessoas trans, independentemente de onde eles se sentam no espectro de gênero. Para pessoas<span>  <span   >AMAB</span>,</span> isso pode se manifestar como um desejo de incorporar elementos mais femininos, e o contrário para pessoas<span>  <span   >AFAB</span>.</span> Isso pode vir como um impulso total em direção ao oposto de seu gênero atribuído, ou um desejo de buscar um meio-termo na busca da androginia. Pode até ser simplesmente um desejo de não se apresentar como seu gênero designado.</p>
   <p><strong>Nem todas as pessoas trans femininas têm uma apresentação feminina, nem todas as pessoas trans masculinas têm uma apresentação masculina e nem todas as pessoas não binárias procuram a androginia. O gênero de alguém e a forma que ele escolhe expressá-lo não são a mesma coisa.</strong></p>
   <p>A disforia com a apresentação geralmente aparece cedo na forma de um enorme interesse pelo estilo de outro gênero e um desejo de ser capaz de se apresentar como as pessoas desse gênero o fazem. Esse desejo pode ser mais ou menos atendido procurando um estilo que seja unissex, mas no geral a pessoa não se sente tão confiante de explorar esse desejo e acaba se auto sabotando ou se podando. Pessoas<span>  <span   >AMAB</span>  </span>em especial costumam ter problemas aqui, pois esse desejo muitas vezes fica preso por trás de expectativas heteronormativas, fazendo com que um interesse na apresentação feminina seja mal interpretado como expressão tipicamente homosexual.</p>
   <p>Após iniciar uma transição de gênero, a tentativa de vestir roupas tipicamente reservadas ao gênero que lhe designaram ao nascer pode causar séria disforia – roupas “masculinas" ressaltam e evidenciam formas corporais “masculinas". Isto é especialmente um problema para pessoas no início da terapia hormonal, quando as mudanças causadas pelo estrogênio ou testosterona ainda não estão completas, e roupas servem um papel importante para sinalizar seu gênero correto.</p>
   <h3 >O efeito da apresentação na disforia física</h3>
   <p>Roupas também podem desempenhar um papel importante no nível de disforia física que uma pessoa experimenta. Roupas masculinas são sempre cortadas bem quadradas, retas para cima e para baixo na vertical e muito quadradas na horizontal. As roupas femininas realçam mais as curvas, acentuando as cinturas e o formato do quadril. Calças masculinas apresentam uma virilha mais baixa para dar espaço aos órgãos genitais, e escondem as curvas do corpo. Roupas femininas costumam ser mais justas no corpo, enquanto roupas masculinas costumam ser mais largas. Roupas masculinas costumam ser feitas de materiais mais resistentes e grossos. Roupas femininas costumam ser feitas de materiais mais finos e elásticos.</p>
   <p>Já que roupas são feitas para se adequar a formatos de corpo masculinos ou femininos (e exagerar ou diminuir certas partes do corpo), elas tendem a amplificar a sensação de incômodo. A diferença entre calças jeans masculinas e femininas, por exemplo, pode ter um efeito radical no nível de conforto de uma pessoa trans. Infelizmente, isso funciona para os dois lados, já que até a experiência de uma pessoa trans de provar roupas do seu verdadeiro gênero pode acentuar incômodos com a percepção de que aquela roupa não se encaixa tão bem no corpo dela.</p>
   <p>Mesmo antes de se perceberem como trans, é comum que as pessoas evitem  certos estilos de roupas e busquem outros que as deixem mais confortáveis com o próprio corpo. Pessoas<span>  <span   >AMAB</span>  </span>podem buscar calças altas e coladas que realcem seu quadril e evitar camisetas regatas, pois acentuam o formato masculino do ombro e os bíceps. Da mesma forma, pessoas trans masculinas podem evitar tops que expõem a barriga, para não atrair atenção ao quadril, o formato feminino do abdômen ou os seios, e buscar usar calças largas e folgadas.</p>
   <p>Neste aspecto, a disforia de gênero, em particular antes de ser notada como tal, tem muito em comum com outros problemas de imagem corporal. Isto costuma resultar em evitar qualquer roupa que realce a forma do corpo, com uma preferência por tecidos mais macios e roupas mais largas de forma a evitar ao máximo qualquer desconforto que lhe faça lembrar do seu corpo. Um exemplo clássico é alguém que não veste nada além de calças de moletom e blusões, roupas superdimensionadas para que não se agarrem ao corpo e escondam sua forma.&nbsp;</p>
   <p>Internamente, a disforia pode se manifestar como uma inveja de pessoas que você gostaria de ser. Inveja pelo formato do corpo de alguém famoso, inveja pelas roupas de outras pessoas e, especialmente, inveja de outras pessoas trans. Parte desse sentimento muitas vezes persiste após a transição, uma vez que essa sensação de “inveja" com frequência é apenas a sensação de querer ser parecida com outras pessoas do seu gênero, algo completamente natural, mesmo para pessoas cis.</p>
   <h3 >O efeito da expressão na disforia social</h3>
   <p>A expressão de gênero pode ser importante para evitar ser reconhecida pelo gênero incorreto (“<Link href="https://pt.wikipedia.org/wiki/Misgendering">misgendering</Link>“), especialmente no início da transição. Muitas pessoas trans sentem a necessidade de performar seu gênero para serem aceitas por quem são, inclinando-se para a apresentação feminina ou masculina mais do que realmente gostariam como uma forma de compensação, a fim de garantir que as pessoas leiam seu gênero corretamente. Aquelas que buscam a transição médica podem descobrir que essa necessidade se torna menos importante à medida que seus corpos mudam e elas se tornam mais capazes de serem percebidas pelo gênero correto sem toda uma performance.</p>
   <p>A apresentação performativa era praticamente necessária antes da reforma do WPATH em 2011; qualquer pessoa que comparecesse a uma consulta médica sem apresentação feminina ou masculina extrema corria o risco de ser rotulada como falsa e perder o direito ao tratamento na Escala de Harry Benjamin. Na verdade, as mulheres trans poderiam inclusive perder o acesso ao seu estrogênio simplesmente por usar jeans e uma blusa em vez de um vestido, ou por não colocar maquiagem suficiente. Desde a revisão dos critérios de diagnóstico WPATH, não é mais esperado que pessoas trans tenham uma expressão de gênero estereotípica (em geral, cis- e heteronormativa) para serem consideradas trans.</p>
   <p>A apresentação é especialmente importante entre crianças pré-púberes, visto que não possuem características sexuais secundárias significativas. Roupas e cabelo são as únicas maneiras que temos de mostrar o gênero de uma criança, tanto que se um bebê simplesmente veste uma camisa rosa, estranhos supõem que seja uma menina. Mesmo as roupas unissex para crianças têm uma forte marcação de gênero por meio de cores e desenhos. Para crianças trans, pode ser extremamente angustiante ser forçada a cortar o cabelo ou ser obrigado a deixá-lo crescer. Negar vestidos a uma menina trans, ou forçar um menino trans masculino a usar vestidos, pode ser debilitante para eles.</p>
</div>
    </article>
  )

export default Expressao;
